components:
  - title: 综述
    name: Docs
    items:
      - title: 介绍
        name: Introduction
      - title: 快速上手
        name: Quickstart
      # - title: 自定义主题
      #   name: CustomizeTheme
      # - title: 常见问题
      #   name: Questions
      - title: 更新日志
        name: Changelog
      - title: 设计资源
        name: Resource
  - title: 组件
    name: Docs
    groups:
      - title: 基础组件
        items:
          - title: 按钮
            name: Button
