on:
  push:
    branches:
      - feat/tiga
  pull_request:
    branches:
      - feat/tiga
    types: [closed]

jobs:
  taro_release_job:
    runs-on: ubuntu-latest
    name: Taro Bundle Release
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Setup Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

      # Get commit message
      - name: Get commit message
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1)
          echo "commitmsg=${COMMIT_MESSAGE}" >> $GITHUB_ENV
      - name: Show commit message
        run : echo "$commitmsg"

      - name: Cache node_modules Folder
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules
          restore-keys: ${{ runner.os }}-node_modules
      - name: Get Yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v2
        env:
          cache-name: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: |
          yarn
      - name: Lerna Bootstrap
        run: |
          yarn bootstrap
      - name: build:component
        # if: startsWith( env.commitmsg , 'chore(release):' )
        run: yarn build:component
      - name: build:rn
        # if: startsWith( env.commitmsg , 'chore(release):' )
        run: yarn build:rn
      - name: Release Taro React Native bundle
        # if: startsWith( env.commitmsg , 'chore(release):' )
        uses: zhiqingchen/taro-react-native-release@v1
        with:
          workingdirectory: ./packages/tiga-ui-demo
          token: ${{ secrets.GITHUB_TOKEN }}
          appname: Tiga-UI-Demo
          logo: https://pic5.58cdn.com.cn/nowater/fangfe/n_v25a185c1657984016926f26af591912c4.jpg
      - name: Upload Qr Image
        uses: actions/upload-artifact@v2
        with:
          name: bundle-qr-code
          path: |
            packages/tiga-ui-demo/release/qrcode/ios.png
            packages/tiga-ui-demo/release/qrcode/android.png
